### ISSUE TITLE
Integration into .github repo in cvxgrp?

### ISSUE THREAD

**Issue by tschm** [cvxpy/actions#1]
I think this could be integrated into the .github repo in cvxgrp.

**Comment by phschiele** [comment]
The reason why we created a new repo is that this repo should eventually contain the build and deploy workflow for cvxpy.
We would like to manage permissions to that independently.
That being said, for something like linting there might be more room to reuse workflows.

**Comment by phschiele** [comment]
Closing this issue here for the reason mentioned above.
