### ISSUE TITLE
Add branch protection

### ISSUE THREAD

**Issue by phschiele** [cvxpy/actions#2]
Currently, this repo has no branch protection rules set up, meaning that any member of the cvxpy org can push directly into `main`. Once we have migrated the workflows, I suggest adding branch protection for `main`.

**Comment by SteveDiamond** [comment]
I added branch protection so all changes to main must go through PRs.

**Comment by phschiele** [comment]
Perfect, thanks! Can you also do the same for `cvxpy/benchmarks`?

**Comment by SteveDiamond** [comment]
Done
